//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MA.Dao.Generate.VSIX.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MA.Dao.Generate.VSIX.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MA.Dal;
        ///using MA.Dao;
        ///using MA.Dao.Entity;
        ///using MA.Dao.Attributes;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel.DataAnnotations;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace MA.Database.Functions.Scalar
        ///{
        ///    [MADataName(Name = &quot;function_database_name&quot;)]
        ///    public class function_name : MADaoViewOrFuncEntity&lt;function_name&gt;
        ///    {
        ///        #region Variables
        ///        [MADataColumn(Name = &quot;&quot;)]
        ///        public function_type da [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FunctionScalar {
            get {
                return ResourceManager.GetString("FunctionScalar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MA.Dal;
        ///using MA.Dao;
        ///using MA.Dao.Entity;
        ///using MA.Dao.Attributes;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel.DataAnnotations;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace MA.Database.Functions.Table
        ///{
        ///    [MADataName(Name = &quot;function_database_name&quot;)]
        ///    public class function_name : MADaoViewOrFuncEntity&lt;function_name&gt;
        ///    {
        ///        #region Variables
        ///        /*function_properties*/
        ///        #endregion
        ///
        ///        #reg [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FunctionTable {
            get {
                return ResourceManager.GetString("FunctionTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MA.Dao;
        ///using MA.Dao.Entity;
        ///using MA.Dao.Attributes;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel.DataAnnotations;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace MA.Database.Procedures
        ///{
        ///    [MADataName(Name = &quot;procedure_database_name&quot;)]
        ///    public class procedure_name : MADaoProcedureEntity&lt;procedure_name, TResult&gt;
        ///    {
        ///        #region Variables
        ///        /*procedure_properties*/
        ///        #endregion
        ///    }
        ///    /*
        ///     Ex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Procedure {
            get {
                return ResourceManager.GetString("Procedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using MA.Dao;
        ///using MA.Dao.Entity;
        ///using MA.Dao.Attributes;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel.DataAnnotations;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace MA.Database.Tables
        ///{
        ///    [MADataName(Name = &quot;table_database_name&quot;)]
        ///    public class table_name : MADaoTableEntity&lt;table_name&gt;
        ///    {
        ///        #region Variables
        ///        /*table_properties*/
        ///        #endregion
        ///    }
        ///    /*
        ///     Examples : 
        ///        Insert Row :
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
    }
}
